# Generated by Django 5.2.7 on 2025-10-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Química', 'Química'), ('Microbiología', 'Microbiología'), ('Dirección', 'Dirección'), ('Proyecto de equipamiento', 'Proyecto de equipamiento')], max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_position',
            field=models.CharField(blank=True, max_length=80, verbose_name='Posición o cargo de trabajo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Teléfono'),
        ),
    ]
