# Generated by Django 5.2.7 on 2025-10-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientocompra',
            name='fecha_final_mant_calib_caract',
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='calibracion',
            field=models.BooleanField(default=False, verbose_name='CALIBRACIÓN'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='caracterizacion',
            field=models.BooleanField(default=False, verbose_name='CARACTERIZACIÓN'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='condicion',
            field=models.CharField(choices=[('recorrido', 'En Recorrido'), ('ingresado_v3', 'Ingresado al V3'), ('evaluado', 'Evaluado'), ('refrendado', 'Refrendado'), ('anulado', 'Anulado'), ('finalizado', 'Finalizado')], max_length=20, verbose_name='CONDICIÓN'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='enlace_orden_compra',
            field=models.URLField(blank=True, max_length=500, verbose_name='ENLACE DE LA ORDEN DE COMPRA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='enlace_sbs',
            field=models.URLField(blank=True, max_length=500, verbose_name='ENLACE DE LA SBS'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='fecha_ingreso_v3',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE INGRESO V3'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='fecha_pedido_evaluado',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE PEDIDO EVALUADO'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='fecha_publicacion_oc',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE PUBLICACIÓN DE LA ORDEN DE COMPRA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='fecha_recibo',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE RECIBO'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='mantenimiento',
            field=models.BooleanField(default=False, verbose_name='MANTENIMIENTO'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='monto_oc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MONTO DE LA ORDEN DE COMPRA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='nuevo_plazo_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='NUEVO PLAZO DE ENTREGA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='numero_ajuste',
            field=models.CharField(blank=True, max_length=50, verbose_name='NÚMERO DE AJUSTE'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='numero_partida',
            field=models.CharField(blank=True, max_length=100, verbose_name='NÚMERO DE PARTIDA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='observacion_1',
            field=models.TextField(blank=True, verbose_name='OBSERVACIÓN 1'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='observacion_2',
            field=models.TextField(blank=True, verbose_name='OBSERVACIÓN 2'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='oc_numero',
            field=models.CharField(blank=True, help_text='Número de la Orden de Compra (4200#######)', max_length=100, verbose_name='NÚMERO DE LA ORDEN DE COMPRA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='plazo_entrega',
            field=models.PositiveIntegerField(blank=True, help_text='Días para realizar la entrega', null=True, verbose_name='PLAZO DE ENTREGA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='proveedor',
            field=models.CharField(blank=True, max_length=256, verbose_name='PROVEEDOR'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='quien_recibe_almacen',
            field=models.CharField(blank=True, help_text='Nombre del que recibe el bien o # de Recibido Conforme', max_length=256, verbose_name='QUIÉN RECIBE EN ALMACÉN / # DE RECIBO CONFORME'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='sbs_numero',
            field=models.CharField(blank=True, help_text='Número de la solicitud de bienes y servicios (###-2026)', max_length=50, verbose_name='NÚMERO DE SBS'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='solicitud_ajuste',
            field=models.TextField(blank=True, verbose_name='SOLICITUD DE AJUSTE'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='status_final_compra',
            field=models.CharField(blank=True, choices=[('Entregado', 'Entregado'), ('Realizado', 'Realizado'), ('Pendiente', 'Pendiente'), ('Por Entregar', 'Por Entregar')], max_length=20, verbose_name='ESTADO FINAL DE LA COMPRA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('Total', 'Total'), ('Parcial', 'Parcial')], max_length=10, verbose_name='TIPO DE ENTREGA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='tipo_plazo',
            field=models.CharField(blank=True, choices=[('Calendario', 'Días Calendario'), ('Habiles', 'Días Hábiles')], max_length=15, verbose_name='TIPO DE PLAZO'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='vencimiento_oc',
            field=models.DateField(blank=True, null=True, verbose_name='VENCIMIENTO DE LA ORDEN DE COMPRA'),
        ),
    ]
