# Generated by Django 5.2.7 on 2025-10-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_remove_seguimientocompra_fecha_final_mant_calib_caract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocompra',
            name='condicion',
            field=models.CharField(blank=True, choices=[('recorrido', 'En Recorrido'), ('ingresado_v3', 'Ingresado al V3'), ('evaluado', 'Evaluado'), ('refrendado', 'Refrendado'), ('anulado', 'Anulado'), ('finalizado', 'Finalizado')], max_length=20, verbose_name='CONDICIÓN'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='fecha_inicial_mant_calib_caract',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA INICIAL'),
        ),
    ]
