# Generated by Django 5.2.7 on 2025-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_seguimientocompra_condicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocompra',
            name='fecha_inicial_mant_calib_caract',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA INICIAL DEL SERVICIO'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='status_final_compra',
            field=models.CharField(blank=True, choices=[('OC - ENTREGADA ***(ENTREGA TOTAL)*** COMPLETADA.', 'OC - ENTREGADA ***(ENTREGA TOTAL)*** COMPLETADA.'), ('OC - PENDIENTE POR ENTREGAR ***(ENTREGA PARCIAL):*** Próxima a completarse.', 'OC - PENDIENTE POR ENTREGAR ***(ENTREGA PARCIAL):*** Próxima a completarse.'), ('OC - SERVICIO REALIZADO ***(ENTREGA TOTAL)***COMPLETADA.', 'OC - SERVICIO REALIZADO ***(ENTREGA TOTAL)***COMPLETADA.'), ('OC - SERVICIO PENDIENTE POR REALIZAR (ENTREGA PARCIAL ):*** Próxima a completarse.', 'OC - SERVICIO PENDIENTE POR REALIZAR (ENTREGA PARCIAL ):*** Próxima a completarse.')], max_length=100, verbose_name='ESTADO FINAL DE LA COMPRA'),
        ),
    ]
