# Generated by Django 5.2.7 on 2025-10-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_seguimientocompra_fecha_inicial_mant_calib_caract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocompra',
            name='monto_oc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='MONTO DE LA ORDEN DE COMPRA'),
        ),
    ]
