# Generated by Django 5.2.7 on 2025-11-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_alter_seguimientocompra_monto_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='ref_departamento',
            field=models.CharField(blank=True, editable=False, help_text='Identificación automática (Ej: M-01-25)', max_length=100),
        ),
    ]
