# Generated by Django 5.2.7 on 2026-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_solicitud_ref_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='urgente',
            field=models.CharField(choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', help_text='Indique si la solicitud requiere trámite urgente', max_length=10),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='status_final_compra',
            field=models.CharField(blank=True, choices=[('OC - POR ENTREGAR', 'OC - POR ENTREGAR'), ('OC - ENTREGADA ***(ENTREGA TOTAL)*** COMPLETADA.', 'OC - ENTREGADA ***(ENTREGA TOTAL)*** COMPLETADA.'), ('OC - PENDIENTE POR ENTREGAR ***(ENTREGA PARCIAL):*** Próxima a completarse.', 'OC - PENDIENTE POR ENTREGAR ***(ENTREGA PARCIAL):*** Próxima a completarse.'), ('OC - SERVICIO REALIZADO ***(ENTREGA TOTAL)***COMPLETADA.', 'OC - SERVICIO REALIZADO ***(ENTREGA TOTAL)***COMPLETADA.'), ('OC - SERVICIO PENDIENTE POR REALIZAR (ENTREGA PARCIAL ):*** Próxima a completarse.', 'OC - SERVICIO PENDIENTE POR REALIZAR (ENTREGA PARCIAL ):*** Próxima a completarse.')], max_length=100, verbose_name='ESTADO FINAL DE LA COMPRA'),
        ),
    ]
