# Generated by Django 5.2.7 on 2026-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_solicitud_urgente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientocompra',
            name='enlace_evaluacion',
            field=models.URLField(blank=True, max_length=500, verbose_name='ENLACE DE EVALUACIÓN'),
        ),
        migrations.AddField(
            model_name='seguimientocompra',
            name='enlace_recibido_conforme',
            field=models.URLField(blank=True, max_length=500, verbose_name='ENLACE DE RECIBIDO CONFORME'),
        ),
        migrations.AddField(
            model_name='seguimientocompra',
            name='numero_recibido_conforme',
            field=models.TextField(blank=True, verbose_name='NÚMERO DE RECIBIDO CONFORME'),
        ),
        migrations.AddField(
            model_name='seguimientocompra',
            name='observacion_ajuste',
            field=models.TextField(blank=True, verbose_name='OBSERVACIÓN DEL AJUSTE'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='enlace_sbs',
            field=models.URLField(blank=True, max_length=500, verbose_name='ENLACE DE LA SBS INGRESADA AL V3'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='fecha_ingreso_v3',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE INGRESO AL V3'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='fecha_recibo',
            field=models.DateField(blank=True, null=True, verbose_name='FECHA DE RECIBIDO EN ALMACÉN'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='oc_numero',
            field=models.CharField(blank=True, max_length=100, verbose_name='NÚMERO DE LA ORDEN DE COMPRA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='plazo_entrega',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PLAZO DE ENTREGA'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='quien_recibe_almacen',
            field=models.TextField(blank=True, verbose_name='QUIÉN RECIBE EN ALMACÉN'),
        ),
        migrations.AlterField(
            model_name='seguimientocompra',
            name='sbs_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='NÚMERO DE SBS'),
        ),
    ]
