# Generated by Django 5.2.7 on 2026-05-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_seguimientocompra_enlace_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocompra',
            name='condicion',
            field=models.CharField(blank=True, choices=[('recorrido', 'En Recorrido'), ('ingresado_v3', 'Ingresado al V3'), ('evaluado', 'Evaluado'), ('refrendado', 'Refrendado'), ('anulado', 'Anulado'), ('finalizado', 'Finalizado')], max_length=255, verbose_name='CONDICIÓN'),
        ),
    ]
